// Generated by https://quicktype.io

export interface Flight {
  type: Type;
  status: Status;
  departure: Arrival;
  arrival: Arrival;
  airline: Airline;
  flight: FlightClass;
  codeshared?: Codeshared;
}

export interface Airline {
  name: string;
  iataCode: string;
  icaoCode?: string;
}

export interface Arrival {
  iataCode: string;
  icaoCode: string;
  terminal?: string;
  gate?: string;
  baggage?: string;
  scheduledTime: string;
  estimatedTime?: string;
  actualTime?: string;
  estimatedRunway?: string;
  actualRunway?: string;
  delay?: number;
}

export interface Codeshared {
  airline: Airline;
  flight: FlightClass;
}

export interface FlightClass {
  number: string;
  iataNumber: string;
  icaoNumber?: string;
}

export enum Status {
  Landed = 'landed',
  Scheduled = 'scheduled',
  Cancelled = 'cancelled',
  Active = 'active',
  Incident = 'incident',
  Diverted = 'diverted',
  Redirected = 'redirected',
  Unknown = 'unknown'
}

export enum Type {
  Arrival = 'arrival'
}
